// Generated by scripts/types.mjs from schema/*.json — do not edit by hand.
// Regenerate with: npm run types
//
// The JSON Schemas are the contract for the data. These declarations are
// derived from them so the two can never disagree.

/** Lower-case kebab-case identifier. Matches the entry's filename. */
export type Slug = string

/** SPDX identifier (MIT, Apache-2.0, ...) or the literal string "proprietary". */
export type SpdxOrProprietary = string

export type GitHubHandle = string

/**
 * How much to trust a field.
 * verified  — checked against the primary standard or tested on real hardware
 * reported  — documented by the vendor or a credible secondary source
 * unverified — community knowledge, needs checking
 */
export type Confidence = "verified" | "reported" | "unverified"

export type Status = "current" | "draft" | "superseded" | "deprecated" | "historical"

export interface Link {
  url: string
  label?: string
}

export interface Port {
  number: number
  transport: "udp" | "tcp" | "sctp"
  role?: string
  iana_registered?: boolean
  note?: string
}

/** Where a fact came from. Every entry carries at least one. */
export interface Source {
  title: string
  url: string
  publisher?: string
  accessed?: string
  /** True if this is the authoritative document, not a summary of it. */
  primary?: boolean
}

/**
 * A wire protocol, transport, or data format used to move control, timing, media, or position data around a live entertainment system.
 */
export interface Protocol {
  id: Slug
  name: string
  /** Other names people actually use on headset. Include the ones that are technically wrong but universally said. */
  aka?: string[]
  category: "lighting-control" | "audio-transport" | "audio-control" | "video-transport" | "video-control" | "media-control" | "show-control" | "timecode-sync" | "tracking-position" | "machinery-motion" | "network-transport" | "device-management" | "power-monitoring"
  /** Two sentences maximum. What it carries, and what it is actually used for on a real job. */
  summary: string
  transport?: ("udp" | "tcp" | "ethernet-l2" | "rs485" | "rs232" | "midi-din" | "usb" | "http" | "websocket" | "fibre" | "wireless-rf" | "other")[]
  default_ports?: Port[]
  multicast?: {
    used?: boolean
    ranges?: string[]
    note?: string
  }
  /** For lighting-control protocols: how addressing works. e.g. '512 slots per universe, universes 1-63999'. */
  universe_model?: string
  /** Can an integrator legally get the spec, and at what cost? This is the field people most often need and least often find. */
  openness: "open-published" | "open-free-registration" | "published-paid" | "proprietary-documented" | "proprietary-closed" | "reverse-engineered"
  spec_url?: Link
  /** IDs of entries in data/standards/ that define this protocol. */
  standards?: Slug[]
  /** Organisation or company that controls the spec. ESTA, AES, SMPTE, Audinate, MA Lighting, ... */
  steward?: string
  first_published?: number
  status: Status
  superseded_by?: Slug
  typical_use?: string[]
  /** The things that bite you at 2am. Be specific and cite where you can. */
  gotchas?: string[]
  /** Open source libraries that speak this protocol, so an integrator does not have to start from zero. */
  implementations?: ({
    name: string
    url: string
    language?: string
    license?: SpdxOrProprietary
    role?: "sender" | "receiver" | "both" | "analyser"
  })[]
  confidence?: Confidence
  tags?: string[]
  sources: Source[]
  contributed_by?: GitHubHandle[]
  updated?: string
  /**
   * Computed at build time: every indexed product that sends or receives this
   * protocol. Not present in the source YAML — it is the reverse of each
   * product's `speaks` array.
   */
  spoken_by?: Speaker[]
}

/**
 * A software tool used to design, control, play back, or monitor a live entertainment system.
 */
export interface Software {
  id: Slug
  name: string
  aka?: string[]
  vendor?: string
  category: "lighting-control" | "media-server" | "video-playback" | "audio-playback" | "audio-mixing" | "show-control" | "cue-playback" | "previsualisation" | "cad-drafting" | "tracking" | "networking-utility" | "monitoring-diagnostics" | "content-creation" | "production-management"
  summary: string
  license: SpdxOrProprietary
  price_model?: "free" | "open-source" | "freemium" | "one-off-purchase" | "subscription" | "dongle-locked" | "quote-only"
  platforms?: ("windows" | "macos" | "linux" | "ios" | "android" | "web" | "embedded")[]
  /** The interop matrix. Which protocols this software can send or receive. This is the single most useful field in the whole index. */
  speaks?: ({
    protocol: Slug
    direction: "in" | "out" | "bidirectional"
    since_version?: string
    /** True if this capability is behind a paid tier or add-on. */
    requires_licence?: boolean
    note?: string
    confidence?: Confidence
  })[]
  homepage?: Link
  repo?: Link
  docs?: Link
  status: Status
  superseded_by?: Slug
  typical_use?: string[]
  gotchas?: string[]
  confidence?: Confidence
  tags?: string[]
  sources: Source[]
  contributed_by?: GitHubHandle[]
  updated?: string
}

/**
 * A physical device in the control, distribution, or playback path of a live entertainment system.
 */
export interface Hardware {
  id: Slug
  name: string
  aka?: string[]
  vendor: string
  category: "lighting-console" | "media-server" | "audio-console" | "video-processor" | "dmx-node" | "network-switch" | "dimmer-distro" | "power-distro" | "tracking-system" | "motion-control" | "show-controller" | "timecode-generator" | "io-interface" | "wireless-dmx"
  summary: string
  speaks?: ({
    protocol: Slug
    direction: "in" | "out" | "bidirectional"
    since_version?: string
    requires_licence?: boolean
    note?: string
    confidence?: Confidence
  })[]
  /** Connectors on the back. e.g. '2x XLR5F DMX out', '2x etherCON Gigabit', '1x BNC wordclock in'. */
  physical_ports?: string[]
  form_factor?: string
  rack_units?: number
  released?: number
  status: Status
  superseded_by?: Slug
  /** IDs of entries in data/software/ that this device runs natively. */
  runs_software?: Slug[]
  homepage?: Link
  docs?: Link
  gotchas?: string[]
  confidence?: Confidence
  tags?: string[]
  sources: Source[]
  contributed_by?: GitHubHandle[]
  updated?: string
}

/**
 * A published technical or safety standard that governs how live entertainment systems are built and operated.
 */
export interface Standard {
  id: Slug
  /** The formal number as printed on the document. e.g. 'ANSI E1.31-2018'. */
  designation: string
  title: string
  /** Publishing body. ESTA, ANSI, AES, SMPTE, IEC, ISO, IEEE, IATSE, BSI, CSA, DIN, ... */
  body: string
  domain: "control-data" | "audio" | "video" | "networking" | "rigging-structural" | "electrical" | "machinery" | "pyro-flame" | "laser" | "safety-management" | "accessibility" | "sustainability"
  year?: number
  /** What the document actually covers, in plain language. */
  scope?: string
  status: Status
  supersedes?: Slug[]
  superseded_by?: Slug
  /** True if the full text can be downloaded at no cost. ESTA publishes many of its ANSI standards free; most other bodies do not. */
  free_to_read?: boolean
  access_url?: Link
  /** Where it is commonly referenced or legally adopted. Use ISO country codes or region names. */
  jurisdiction?: string[]
  related_protocols?: Slug[]
  notes?: string
  confidence?: Confidence
  tags?: string[]
  sources: Source[]
  contributed_by?: GitHubHandle[]
  updated?: string
}

/**
 * A piece of live entertainment vocabulary, with the translations crews actually use rather than the dictionary ones.
 */
export interface Term {
  id: Slug
  en: string
  /** Traditional Chinese as used in HK / TW crews. */
  zh_hant?: string
  zh_hans?: string
  ja?: string
  ko?: string
  de?: string
  fr?: string
  es?: string
  /** Same job, different word depending on where you are standing. */
  regional_variants?: {
    region: string
    term: string
    note?: string
  }[]
  domain: "lighting" | "audio" | "video" | "rigging" | "stage-management" | "automation" | "scenic" | "wardrobe" | "production-management" | "networking" | "safety" | "general"
  definition_en: string
  definition_zh_hant?: string
  /** Terms that look like they mean the same thing and do not. The reason this file exists. */
  false_friends?: string[]
  see_also?: Slug[]
  related_protocols?: Slug[]
  /** True if getting this word wrong on headset can hurt someone. Rendered with a warning on the site. */
  safety_critical?: boolean
  confidence?: Confidence
  tags?: string[]
  sources: Source[]
  contributed_by?: GitHubHandle[]
  updated?: string
}

/** One product's ability to speak a protocol, as recorded on the protocol. */
export interface Speaker {
  kind: 'software' | 'hardware'
  id: Slug
  name: string
  vendor: string | null
  direction: 'in' | 'out' | 'bidirectional'
  requires_licence: boolean
  confidence: Confidence
  note: string | null
}

/** Any indexed product, software or hardware, tagged with which it is. */
export type Product = (Software | Hardware) & { kind: 'software' | 'hardware' }

/** A field we know is missing. The contributor backlog, generated not curated. */
export interface Gap {
  collection: CollectionKey
  id: Slug
  name: string
  missing: string[]
}

export interface Contributor {
  handle: GitHubHandle
  entries: number
}

export type CollectionKey = "protocols" | "software" | "hardware" | "standards" | "terms"

/** A path over which one product can reach another. */
export interface InteropPath {
  from: Slug
  to: Slug
  protocol: Slug
}

export interface Meta {
  generated: string
  counts: Record<CollectionKey, number>
  total: number
}

export declare const protocols: Protocol[]
export declare const software: Software[]
export declare const hardware: Hardware[]
export declare const standards: Standard[]
export declare const terms: Term[]
export declare const products: Product[]
export declare const contributors: Contributor[]
export declare const gaps: Gap[]
export declare const meta: Meta

/**
 * What is listening on this port?
 * The question you ask when a capture shows traffic you did not expect.
 */
export declare function byPort(number: number | string, transport?: 'udp' | 'tcp' | 'sctp'): Protocol[]

/**
 * Everything indexed that sends or receives a given protocol.
 * Passing a direction includes bidirectional devices, because a device that
 * can do both can certainly do the one you asked about.
 */
export declare function whoSpeaks(protocolId: Slug, direction?: 'in' | 'out'): Speaker[]

/** Can these two products talk, and over what? Returns both directions. */
export declare function interop(idA: Slug, idB: Slug): InteropPath[]

/** Look up a glossary term by slug, English, or Chinese. */
export declare function term(query: string): Term[]

export declare function get(collection: 'protocols', id: Slug): Protocol | null
export declare function get(collection: 'software', id: Slug): Software | null
export declare function get(collection: 'hardware', id: Slug): Hardware | null
export declare function get(collection: 'standards', id: Slug): Standard | null
export declare function get(collection: 'terms', id: Slug): Term | null
export declare function get(collection: string, id: Slug): unknown | null

export interface SearchOptions {
  collection?: CollectionKey
  limit?: number
}

/** Substring search across everything, including ports and Chinese terms. */
export declare function search(
  query: string,
  options?: SearchOptions
): Array<{ collection: CollectionKey } & Record<string, unknown>>

/** Everything we know is missing, optionally filtered to one collection. */
export declare function missing(collection?: CollectionKey): Gap[]

declare const _default: {
  protocols: Protocol[]
  software: Software[]
  hardware: Hardware[]
  standards: Standard[]
  terms: Term[]
  products: Product[]
  contributors: Contributor[]
  gaps: Gap[]
  meta: Meta
  byPort: typeof byPort
  whoSpeaks: typeof whoSpeaks
  interop: typeof interop
  term: typeof term
  get: typeof get
  search: typeof search
  missing: typeof missing
}
export default _default
